### ISSUE TITLE
DLL error on install

### ISSUE THREAD

**Issue by Heartss** [maxdeviant/lol-mastery-manager#12]
Can't install the .msi, says a dll could be not run
![mastery](https://cloud.githubusercontent.com/assets/10832394/10442302/37920a3c-7151-11e5-967b-fabc369216d6.jpg)

**Comment by maxdeviant** [comment]
Could you check what version of .NET Framework you're running? It should require [.NET 4.5.2](http://www.microsoft.com/en-us/download/details.aspx?id=42642).

Also, there is now a [portable version](https://github.com/maxdeviant/lol-mastery-manager/releases/download/v1.1.1/LoLMasteryManager-1.1.1.zip) which you could try.

**Comment by Heartss** [comment]
I have .NET 4.6.

The portable version works perfect so I'll stick with that.

**Comment by maxdeviant** [comment]
Great!
