### ISSUE TITLE
Installer with Inno Setup

### ISSUE THREAD

**Issue by LOLfan** [maxdeviant/lol-mastery-manager#13]
Could u create installer with Inno Setup? Cuz present installer is kind of not user friendly and not comfortable ;)

**Comment by maxdeviant** [comment]
I have never worked with Inno Setup before. I suppose I could look into it.

I personally don't see any issues with the current installer though :wink:

**Comment by LOLfan** [comment]
@maxdeviant 
Clean Inno Setup could be difficult cuz there is a lot of programming language in it. But u can use awesome GUI, here is the link: https://www.kymoto.org/products/inno-script-studio/screenshots
I dont insist but u can try if u have time and mood for it xD

**Comment by maxdeviant** [comment]
Yea, this seems like a lot of work haha.

Setting up the installer in Visual Studio took me less than 15 minutes, and I just need to recompile every time I make a change :)

**Comment by LOLfan** [comment]
@maxdeviant
If u doing this in Visual Studio and it's fastest way for u then np :D
I though u making your soft in eg. Visual Studio and creating setup in separate softtware :)
