### ISSUE TITLE
Application crashes as soon as it opens

### ISSUE THREAD

**Issue by manjot97** [maxdeviant/lol-mastery-manager#17]
So today I opened the app, and it said downloading champion.gg data, then it stopped responding and windows said that an unexpected error occured, any fix?

**Comment by maxdeviant** [comment]
The new mastery format for 5.22 is probably causing an error to occur while downloading the mastery data.

This will need to be addressed in a release for patch 5.22.

**Comment by DiteVQ** [comment]
The same happened to me

**Comment by manjot97** [comment]
Champion.gg released data for 5.22 So how long until the application will work again?

**Comment by maxdeviant** [comment]
Once I start work on it the turn-around should be a few days.

But I'm extremely busy currently with school and work, and probably won't
get to it until after Wednesday. Would like to release by Monday, but
that's entirely dependent on the scope of work involved.

**Comment by DiteVQ** [comment]
http://champion.gg/ also they have some problems with your page

**Comment by maxdeviant** [comment]
If you're referring to the "We are currently fixing issues with Jungle builds." across the top, I believe that is to the incorrect items being shown in the build path.

The actual format of the mastery data should be fine for me to start working with.

**Comment by DiteVQ** [comment]
a ok, good job indeed we are patiently waiting for the application

**Comment by manjot97** [comment]
Dude, you're doing a great job. Never would want to invade into your time. School and work are more important :)

**Comment by maxdeviant** [comment]
Closing this in favor of #18, which is better representative of the reason behind the crash.

Follow that thread for 5.22 status/updates.
