### ISSUE TITLE
Crashes upon startup

### ISSUE THREAD

**Issue by DaTaco156002** [maxdeviant/lol-mastery-manager#21]
My client now crashes upon start up.

**Comment by btull89** [comment]
Same for me.

**Comment by jpm1993** [comment]
Same issue here. Maybe due to the new mastery Assassin?

**Comment by GNAAAAR** [comment]
Same on my side :s

**Comment by hiiambo** [comment]
Update your Masteries.json to the following link and it should allow you to start the application:

https://github.com/noslrac/lol-mastery-manager/commit/0b4c88355410a52b2687951498918f37c3273663

**Comment by jpm1993** [comment]
Excuse me, but I'm not very familiar with github. How exactly do I use this
to update my mastery manager?

**Comment by SXRWahrheit** [comment]
@hiiambo - That didn't seem to work for me. :(

**Comment by maxdeviant** [comment]
Fixed as of d621f1d46c4b917f3ccf9ca856f0895d7936cc9f.
