### ISSUE TITLE
Mastery assignment not working at different client sizes

### ISSUE THREAD

**Issue by maxdeviant** [maxdeviant/lol-mastery-manager#5]

**Comment by LOLfan** [comment]
@maxdeviant
So I think that's why it isn't working for me... I see only cursor moves but nothing happens with my points :(

**Comment by maxdeviant** [comment]
@LOLfan The good news is that it's very fixable! I'm actually pretty close to having this done, but it will require a bit more work tonight to finish it up.

**Comment by LOLfan** [comment]
@maxdeviant 
Glad to hear that. I'm waiting for fix. Thank You for info :)

**Comment by maxdeviant** [comment]
This is partially fixed as of v1.1.1.

Still some work to be done on the champion select screen.

**Comment by LOLfan** [comment]
@maxdeviant
I checked last v1.1.2 version and it still doesn't work for me :(
Maybe u can add option to restore default launcher window size?
